added Error Component
CaptainObjective/Meme-Poker pull request #85
Opened 2020-07-28 22:28 UTC by Tom-Bul

2020-08-02 21:28 UTC, CaptainObjective requested changes
Generalnie spoko ale nie możemy wykorzystywać roomContext do przekazywania informacji o błędzie. Tak jak napisałem niżej, uważam ze powinnśmy errorbox podzielić na dwa ui i logika osobno, w ramach room Context wykorzystamy tylko część UI. Uprości nam też to znaczeni logikę bo widzę że tam w wielu miejscach mamy trochę spaghetti bo ten błąd może przyjść na wiele sposóbów

2020-08-02 21:28 UTC, CaptainObjective commented on client/src/App.jsx
> +import ErrorBox from 'Components/ErrorBox/ErrorBox';
```suggestion
import ErrorBox from 'Components/ErrorBox';

```

2020-08-02 21:28 UTC, CaptainObjective commented on client/src/Components/CreateNewRoom/CreateNewRoom.jsx
> +import { useRoomContext } from 'Contexts/RoomContext';
Nie podoba mi się że to korzysta z room context. Jeżeli już chcemy wykorzystać kontekst do przechwytywania informacji to powinniśmy raczej stworzyć osobny context.  W tym konkretnym przypadku jednak zastanowiłbym się na wy renderowaniu snackbara z tego komponentu. Wtedy trzeba było część wizualną z ErrorBoxa wydzielić do nowego komponentu i użyć go w dwóch miejscach

2020-08-02 21:28 UTC, CaptainObjective commented on client/src/Components/CreateNewRoom/CreateNewRoom.jsx
> +      if (currentRoom.data?.room?.id) history.push(`/room/${currentRoom.data.room.id}/join`, { isAdmin: true });
Rozumiem dlaczego musiałeś tu ifa napisać ale generalnie to axios kiedy response code jest >= 400 rzuca błędem. I to właśnie wtedy (w sekcji catch) powinniśmy decydować o wy renderowaniu błędu.

Tu musiałeś to tak zrobić bo na back-endzie błąd jest zwracany ze kodem 200 (czyli że niby wszystko ok). Proponowałbym to poprawić w ramach tego brancha byś mógł już pozbyć się ifa. By to zrobić w pliku session.ts dwunastą linie trzeba podmienić na `    res.status(500).json(ex.message);`

2020-08-06 20:50 UTC, CaptainObjective requested changes
Fajnie że mamy UI w osobnym komponencie teraz spróbujmy go użyć w ramach komponentu logicznego

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/App.jsx
> +import ErrorSocket from 'Components/ErrorBox/ErrorSocket';
ten import można uprościć, 'Components/ErrorBox/';

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/Components/CreateNewRoom/CreateNewRoom.jsx
> +  const [error, setError] = useState(undefined);
Ustawianie zmiennej ręcznie na undefined jest raczej złą praktyką. Dużo bardziej widziałbym jakiegoś nulla w tym miejscu (jeśli w samej zmiennej chcesz przechowywać obiekt z błędem lub tekst błędu). Jeżeli ten stan ma być typu bool to bardziej widzę tu false i zmianę nazwy na isError

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/Components/CreateNewRoom/CreateNewRoom.jsx
> +        setError(undefined);
j.w bardziej coś w stylu setIsException(false)

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/Components/CreateNewRoom/CreateNewRoom.jsx
> +        {error ? <ErrorProp content="Error: Not enough rooms" /> : null}
Można wykorzystać sztuczkę (i często się to robi)
```suggestion
        {error && <ErrorProp content="Error: Not enough rooms" /> }
```

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/Components/ErrorBox/ErrorProp.jsx
> +const ErrorProp = props => {
Nie jestem fanem tej nazwy, może ExceptionBox?

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/Components/ErrorBox/ErrorSocket.jsx
> +const ErrorSocket = () => {
Może nazwijmy to ExceptionHandler?

2020-08-06 20:50 UTC, CaptainObjective commented on client/src/Components/ErrorBox/ErrorSocket.jsx
>      <div>
Tutaj właśnie powinien zostać wykorzystany ten komponent który zrobiłeś (ten z samym wyglądem)

2020-08-10 11:01 UTC, Tom-Bul commented on client/src/Components/CreateNewRoom/CreateNewRoom.jsx
> +        {isLoading && <Loader text="Loading..." />}
Przesunąłem tutaj funkcję z componentem Loader ponieważ gdy występował błąd, ExceptionBox nie miał kiedy się wyrenderować, przez co nigdy się nie pojawiał.

2020-08-24 18:49 UTC, merged