fix types
CaptainObjective/Meme-Poker pull request #91
Opened 2020-08-01 11:04 UTC by maciekkwiet

2020-08-04 19:23 UTC, CaptainObjective requested changes
Kod się kompiluje ale przy okazji ryzykujemy błędem parsując stringi do inta za pomocą parseInt

2020-08-04 19:23 UTC, CaptainObjective commented on server/src/models/Task.ts
> +    this.finalResult = voteValues.map(result => parseInt(result, 10)).reduce((a, b) => a + b, 0) / voteValues.length;
W ten sposób wrzucasz NaN do tablicy, właśnie trzeba zrobić tak by voteValues było już tablicą liczb czyli results bez głosów które nie są liczbami

2020-08-04 19:23 UTC, CaptainObjective commented on server/src/models/Task.ts
> +      if (result.vote !== null) voteValues.push(result.vote);
Może właśnie to sprawdzenie czy nie jest nullem możemy przenieść do Analysis, bo tam już i tak musimy zwalidować input

2020-08-05 00:06 UTC, maciekkwiet commented on server/src/models/Task.ts
> +    this.finalResult = voteValues.map(result => parseInt(result, 10)).reduce((a, b) => a + b, 0) / voteValues.length;
Ta metoda nie jest jednak nigdzie używana xD

2020-08-06 12:00 UTC, merged